# Generated by Django 3.0.14 on 2022-09-25 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='date',
        ),
        migrations.AddField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 25, 23, 14, 43, 329693)),
        ),
    ]
