# Generated by Django 3.0.14 on 2022-09-25 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220925_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 25)),
        ),
    ]
